apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-deployment  # Name of the deployment
  labels:
    app: custom  # Label for the deployment
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: custom  # Selector to match pods with this label
  template:
    metadata:
      labels:
        app: custom  # Labels for the pod template
    spec:
      containers:
      - name: custom  # Name of the container
        image: ln1293/capstone_image  # Docker image for the container
        ports:
        - containerPort: 80  # Port exposed by the container
